[package]
name = "fireflydroid"
version = "0.1.0"
edition = "2024"
autobins = false

[lib]
path = "src/main.rs"
crate-type = ["cdylib"]

[dependencies]
kaolin = { path = "../kaolin"}
macroquad = "0.4.14"
miniserde = "0.1.45"
ureq = "3.1.4"
wasmi = "1.0.7"
